/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiPublicLinkedinLogoutRouteImport } from './routes/api/public/linkedin/logout'
import { Route as ApiPublicLinkedinLoginRouteImport } from './routes/api/public/linkedin/login'
import { Route as ApiPublicLinkedinCallbackRouteImport } from './routes/api/public/linkedin/callback'
import { Route as ApiPublicHooksPublishScheduledRouteImport } from './routes/api/public/hooks/publish-scheduled'
import { Route as ApiPublicHooksAutopilotRouteImport } from './routes/api/public/hooks/autopilot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLinkedinLogoutRoute = ApiPublicLinkedinLogoutRouteImport.update({
  id: '/api/public/linkedin/logout',
  path: '/api/public/linkedin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkedinLoginRoute = ApiPublicLinkedinLoginRouteImport.update({
  id: '/api/public/linkedin/login',
  path: '/api/public/linkedin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkedinCallbackRoute =
  ApiPublicLinkedinCallbackRouteImport.update({
    id: '/api/public/linkedin/callback',
    path: '/api/public/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublishScheduledRoute =
  ApiPublicHooksPublishScheduledRouteImport.update({
    id: '/api/public/hooks/publish-scheduled',
    path: '/api/public/hooks/publish-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutopilotRoute = ApiPublicHooksAutopilotRouteImport.update({
  id: '/api/public/hooks/autopilot',
  path: '/api/public/hooks/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/linkedin/login': typeof ApiPublicLinkedinLoginRoute
  '/api/public/linkedin/logout': typeof ApiPublicLinkedinLogoutRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/linkedin/login': typeof ApiPublicLinkedinLoginRoute
  '/api/public/linkedin/logout': typeof ApiPublicLinkedinLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/linkedin/login': typeof ApiPublicLinkedinLoginRoute
  '/api/public/linkedin/logout': typeof ApiPublicLinkedinLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/linkedin/callback'
    | '/api/public/linkedin/login'
    | '/api/public/linkedin/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/linkedin/callback'
    | '/api/public/linkedin/login'
    | '/api/public/linkedin/logout'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/publish-scheduled'
    | '/api/public/linkedin/callback'
    | '/api/public/linkedin/login'
    | '/api/public/linkedin/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAutopilotRoute: typeof ApiPublicHooksAutopilotRoute
  ApiPublicHooksPublishScheduledRoute: typeof ApiPublicHooksPublishScheduledRoute
  ApiPublicLinkedinCallbackRoute: typeof ApiPublicLinkedinCallbackRoute
  ApiPublicLinkedinLoginRoute: typeof ApiPublicLinkedinLoginRoute
  ApiPublicLinkedinLogoutRoute: typeof ApiPublicLinkedinLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/linkedin/logout': {
      id: '/api/public/linkedin/logout'
      path: '/api/public/linkedin/logout'
      fullPath: '/api/public/linkedin/logout'
      preLoaderRoute: typeof ApiPublicLinkedinLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/linkedin/login': {
      id: '/api/public/linkedin/login'
      path: '/api/public/linkedin/login'
      fullPath: '/api/public/linkedin/login'
      preLoaderRoute: typeof ApiPublicLinkedinLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/linkedin/callback': {
      id: '/api/public/linkedin/callback'
      path: '/api/public/linkedin/callback'
      fullPath: '/api/public/linkedin/callback'
      preLoaderRoute: typeof ApiPublicLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-scheduled': {
      id: '/api/public/hooks/publish-scheduled'
      path: '/api/public/hooks/publish-scheduled'
      fullPath: '/api/public/hooks/publish-scheduled'
      preLoaderRoute: typeof ApiPublicHooksPublishScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/autopilot': {
      id: '/api/public/hooks/autopilot'
      path: '/api/public/hooks/autopilot'
      fullPath: '/api/public/hooks/autopilot'
      preLoaderRoute: typeof ApiPublicHooksAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAutopilotRoute: ApiPublicHooksAutopilotRoute,
  ApiPublicHooksPublishScheduledRoute: ApiPublicHooksPublishScheduledRoute,
  ApiPublicLinkedinCallbackRoute: ApiPublicLinkedinCallbackRoute,
  ApiPublicLinkedinLoginRoute: ApiPublicLinkedinLoginRoute,
  ApiPublicLinkedinLogoutRoute: ApiPublicLinkedinLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
