/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksPublishScheduledRouteImport } from './routes/api/public/hooks/publish-scheduled'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPublishScheduledRoute =
  ApiPublicHooksPublishScheduledRouteImport.update({
    id: '/api/public/hooks/publish-scheduled',
    path: '/api/public/hooks/publish-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/publish-scheduled': typeof ApiPublicHooksPublishScheduledRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/hooks/publish-scheduled'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/hooks/publish-scheduled'
  id: '__root__' | '/' | '/api/public/hooks/publish-scheduled'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksPublishScheduledRoute: typeof ApiPublicHooksPublishScheduledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-scheduled': {
      id: '/api/public/hooks/publish-scheduled'
      path: '/api/public/hooks/publish-scheduled'
      fullPath: '/api/public/hooks/publish-scheduled'
      preLoaderRoute: typeof ApiPublicHooksPublishScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksPublishScheduledRoute: ApiPublicHooksPublishScheduledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
